version: '2'

services:
  sonarqube:
    image: sonarqube:7.9.4-community
    restart: always
    ports:
        - "9000:9000"
    links:
        - postgres
    environment:
        - SONARQUBE_JDBC_URL:jdbc:postgresql://db:5432/sonar

  postgres:
    image: postgres:9.6.15
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar