version: '3'
services:
 bitbucket:
  image: atlassian/bitbucket-server:6.6.2-ubuntu
  container_name: bitbucket
  restart: always
  ports:
   - "7990:7990"
   - "7999:7999"
  environment:
   - BITBUCKET_HOME=/var/atlassian/application-data/bitbucket/
  volumes:
   - ./data:/var/atlassian/application-data/bitbucket