version: '3.1'
services:
    coredns:
        image: coredns/coredns:1.9.3
        container_name: coredns
        restart: always
        expose:
            - '53'
            - '53/udp'
        ports:
            - '53:53'
            - '53:53/udp'
        volumes:
            - './Corefile:/Corefile'