version: '2'

services:
    mongodb:
      image: mongo:4.0.12
      container_name: mongodb4012
      restart: always
      ports:
        - 27017:27017
      environment:
        - MONGO_INITDB_DATABASE=test
        - MONGO_INITDB_ROOT_USERNAME=root
        - MONGO_INITDB_ROOT_PASSWORD=root
      volumes:
          - ./data:/data/db

    mongo-express:
      links:
        - mongodb
      image: mongo-express
      restart: always
      ports:
        - 8381:8081
      environment:
        ME_CONFIG_MONGODB_SERVER: mongodb
        ME_CONFIG_OPTIONS_EDITORTHEME: 3024-night
        ME_CONFIG_BASICAUTH_USERNAME: mongoexpress
        ME_CONFIG_BASICAUTH_PASSWORD: mongoexpress
        ME_CONFIG_MONGODB_ADMINUSERNAME: root
        ME_CONFIG_MONGODB_ADMINPASSWORD: root
