version: '2.0'

services:
  nginx:
    restart: always
    image: nginx:1.20
    ports:
      - 80:80
      - 443:443
    environment:
      DOMAIN: domain.com
      BACKEND: http://1.1.1.1:8000
    volumes:
      - ./conf.d/:/etc/nginx/conf.d/
      - ./cert:/usr/local/nginx/cert
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'" 

