# nerdctl run -d --name proxy --restart=always -p 5000:5000 -v $(pwd)/stream:/opt/nginx/stream.conf.d tekn0ir-nginx-stream:latest

version: '2.0'

services:
  nginx:
    restart: always
    image: shaowenchen/demo-nginx-stream:latest
    ports:
      - 5000:5000
    volumes:
      - ./stream:/opt/nginx/stream.conf.d
