version: '3'

services:
  jenkins:
    image: jenkins/jenkins:latest
    container_name: jenkins
    restart: always
    network_mode: "bridge"
    ports:
      - 18080:8080  
      - 50000:50000  
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./data:/var/jenkins_home
