version: '3'
services:
  artifactory:
    image: docker.bintray.io/jfrog/artifactory-oss:latest
    container_name: artifactory
    restart: always
    network_mode: "bridge"
    ports:
     - 8081:8081
     - 8082:8082
    volumes:
     - ./data:/var/opt/jfrog/artifactory
    environment:
     - EXTRA_JAVA_OPTIONS=-Xms512m -Xmx4g
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000

# artifactory-oss:latest
# artifactory-cpp-ce:latest
# artifactory-pro:latest
